var message: string = "Hello world";
console.log(message);

var Name:string = "John"; 
var score1:number = 50;
var score2:number = 42.50
var sum = score1 + score2 
console.log("Name"+Name) 
console.log("first score: "+score1) 
console.log("second score: "+score2) 
console.log("sum of the scores: "+sum)
var n:number = 5
while(n > 5) { 
   console.log("Entered while") 
} 
do { 
   console.log("Entered do…while") 
} 
while(n>5)


//Generated by typescript 1.8.10
var i = 1;

while (i <= 10) {
    if (i % 5 == 0) {
        console.log("The first multiple of 5  between 1 and 10 is : " + i);
        break; //exit the loop if the first multiple is found
    }
   i++;
} //outputs 5 and exits the loop

var num:number = 0
var count:number = 0;

for(num=0;num<=20;num++) {
   if (num % 2==0) {
      continue
   }
   count++
}
console.log (" The count of odd values between 0 and 20 is: "+count)




///function

function disp_details(id:number, name:string, mail_id?: string) {
    console.log("ID: ", id);
    console.log("Name: ", name);
    if(mail_id != undefined)
        console.log("Mail Id ", mail_id);
}

disp_details(123, "John");
disp_details(111, "Mary", "mary@xyz.com");