var message = "Hello world";
console.log(message);
var Name = "John";
var score1 = 50;
var score2 = 42.50;
var sum = score1 + score2;
console.log("Name" + Name);
console.log("first score: " + score1);
console.log("second score: " + score2);
console.log("sum of the scores: " + sum);
